[profile.default]
src = "src"
out = "out"
cache_path = "cache"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read", path = "puzzles.json" }]